name: auto repo pull

concurrency: 
  group: production
  cancel-in-progress: true
  
on:
  push:
      branches: [ main ]
jobs:
  pull-job:
    name: update-server
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        run: git pull
        working-directory: /gitaction_test
